services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=weatherappdb
    command: ["postgres", "-c", "log_statement=all"] 
  redis:
    image: redis:latest
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgresuser:postgrespassword@postgres/weatherappdb
    ports:
      - 8000:8000
    volumes:
      - ./:/app