services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=weatherappdb
    command: ["postgres", "-c", "log_statement=all"] 
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgresuser:postgrespassword@postgres/weatherappdb
      - ROCKET_DATABASES={postgres={url=postgres://postgresuser:postgrespassword@postgres/weatherappdb}}
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./target:/app/target
      - ./shared:/app/shared
    env_file: 
      - ./backend/.env
volumes:
  target:
