services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile 
    volumes:
      - ./shared:/app/shared
      - ./backend:/app/backend
    ports:
      - 8000:8000
  # frontend:
  #   build: 
  #     context: .
  #     dockerfile: frontend/Dockerfile 
  #   volumes:
  #     - ./shared:/app/shared 
  #     - ./frontend:/app/frontend
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - TRUNK_WATCH_USE_POLLING=true
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgresuser 
      - POSTGRES_PASSWORD=postgrespassword 
      - POSTGRES_DB=weatherappdb
    ports:
      - 8080:8080
  redis:
    image: redis:latest 
    ports:
      - 6379:6379
