[default]
address = "0.0.0.0"
port = 8000


[default.oauth.auth0]
auth_uri = "https://dev-kr7vi67c2vo4vs3w.eu.auth0.com/authorize"
token_uri = "https://dev-kr7vi67c2vo4vs3w.eu.auth0.com/oauth/token"
client_id = "QlaL5COscZ8iXYSQIoUp7RWkCZQJ9Y4n"
client_secret = "gIivCoGCBupXKBLlsApY836NPWd1m39UrWnbtz3VOJAgjLSq38qbB__wBVWe4L39"
redirect_uri = "http://127.0.0.1:8000/auth0/callback"